// This file is generated by npm run build:icons
 
export type IconName =
	| "cart"
	| "close"
	| "combo"
	| "deserts"
	| "downArrow"
	| "drinks"
	| "facebooksvg"
	| "fire"
	| "instagram"
	| "logoMain"
	| "phone"
	| "pin"
	| "pizza"
	| "signIn"
	| "snack"
	| "souce"
	| "sushi";
