import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/Layout/Header";
import { PreloadResources } from "../../../preload-resources";
import Fotter from "@/components/Layout/Fotter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PreloadResources />
      <body className={inter.className}>
        <Header />
        {children}
        <Fotter />
      </body>
    </html>
  );
}
